on: pull_request

jobs:
  check-branch:
    runs-on: ubuntu-latest
    name: Comment if target branch is main
    steps:
      - uses: thollander/actions-comment-pull-request@v1
        if: ${{ github.base_ref == 'main' }}
        with:
          message: 'PR의 target 브랜치가 main입니다. PR 우측 상단 Edit를 눌러 base 브랜치를 변경해주세요.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
